import { Injectable, signal, computed } from '@angular/core';
import { PlayerMoniker } from '../models/moniker.model';

@Injectable({
  providedIn: 'root',
})
export class MonikerService {
  private readonly monikersList = signal<PlayerMoniker[]>([
    {
      id: 'mikhail-tal',
      moniker: 'The Magician from Riga',
      playerName: 'Mikhail Tal',
      fideTitle: '8th World Champion',
      years: '1936 – 1992',
      imageUrl: 'assets/player-profiles/mikhail-tal.webp',
      shortDescription: 'Renowned for his hypnotic tactical combinations and willingness to sacrifice pieces for dynamic initiative.',
      blogSlug: 'the-magician-from-riga-mikhail-tal',
      category: 'World Champions',
      tags: ['Tactical', 'Sacrifices', 'World Champion'],
      featured: true,
    },
    {
      id: 'garry-kasparov',
      moniker: 'The Beast from Baku',
      playerName: 'Garry Kasparov',
      fideTitle: '13th World Champion',
      years: '1963 – Present',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Garry_Kasparov_2003.jpg/440px-Garry_Kasparov_2003.jpg',
      shortDescription: 'Dominated international chess for two decades with fierce tactical aggression, deep opening preparation, and unmatched energy.',
      blogSlug: 'the-beast-from-baku-garry-kasparov',
      category: 'World Champions',
      tags: ['Aggressive', 'Opening Preparation', 'World Champion'],
      featured: true,
    },
    {
      id: 'magnus-carlsen',
      moniker: 'The Mozart of Chess',
      playerName: 'Magnus Carlsen',
      fideTitle: '16th World Champion',
      years: '1990 – Present',
      imageUrl: 'assets/player-profiles/magnus-carlsen.webp',
      shortDescription: 'Dubbed "The Mozart of Chess" in his youth for intuitive brilliance, famous for grinding winnable endgame advantages out of equal positions.',
      blogSlug: 'the-mozart-of-chess-magnus-carlsen',
      category: 'Modern Super GMs',
      tags: ['Intuition', 'Endgames', 'World Champion'],
      featured: true,
    },
    {
      id: 'tigran-petrosian',
      moniker: 'The Iron Tigran',
      playerName: 'Tigran Petrosian',
      fideTitle: '9th World Champion',
      years: '1929 – 1984',
      imageUrl: 'assets/player-profiles/tigran-petrosian.webp',
      shortDescription: 'Master of prophylactic defense and exchange sacrifices, virtually impenetrable with an ironclad defensive style.',
      blogSlug: 'the-iron-tigran-petrosian',
      category: 'Positional Legends',
      tags: ['Prophylaxis', 'Defense', 'World Champion'],
      featured: false,
    },
    {
      id: 'jose-raul-capablanca',
      moniker: 'The Chess Machine',
      playerName: 'José Raúl Capablanca',
      fideTitle: '3rd World Champion',
      years: '1888 – 1942',
      imageUrl: 'assets/player-profiles/jose-raul-capablanca.webp',
      shortDescription: 'Famed for effortless natural play, flawless endgame technique, and going eight consecutive years without losing a single serious game.',
      blogSlug: 'the-chess-machine-capablanca',
      category: 'Historical Icons',
      tags: ['Endgames', 'Intuitive', 'World Champion'],
      featured: false,
    },
    {
      id: 'anatoly-karpov',
      moniker: 'The Boa Constrictor',
      playerName: 'Anatoly Karpov',
      fideTitle: '12th World Champion',
      years: '1951 – Present',
      imageUrl: 'assets/player-profiles/anatoly-karpov.webp',
      shortDescription: 'Exerted suffocating positional pressure, gradually minimizing opponent counterplay until their position collapsed under tension.',
      blogSlug: 'the-boa-constrictor-anatoly-karpov',
      category: 'World Champions',
      tags: ['Positional', 'Prophylaxis', 'World Champion'],
      featured: false,
    },
    {
      id: 'bobby-fischer',
      moniker: 'The Lone Wolf of Brooklyn',
      playerName: 'Robert James Fischer',
      fideTitle: '11th World Champion',
      years: '1943 – 2008',
      imageUrl: 'assets/player-profiles/robert-james-fischer.webp',
      shortDescription: 'Single-handedly challenged Soviet chess hegemony, driven by obsessive clarity, lethal precision, and uncompromising spirit.',
      blogSlug: 'the-lone-wolf-bobby-fischer',
      category: 'World Champions',
      tags: ['Precision', 'Relentless', 'World Champion'],
      featured: true,
    },
    {
      id: 'paul-morphy',
      moniker: 'The Pride and Sorrow of Chess',
      playerName: 'Paul Morphy',
      fideTitle: 'Unofficial World Champion',
      years: '1837 – 1884',
      imageUrl: 'assets/player-profiles/paul-morphy.webp',
      shortDescription: 'Decades ahead of his time in development speed and open lines, he dominated the chess world before retiring early at age 22.',
      blogSlug: 'the-pride-and-sorrow-paul-morphy',
      category: 'Historical Icons',
      tags: ['Romantic Era', 'Development', 'Pioneer'],
      featured: false,
    },
    {
      id: 'vishy-anand',
      moniker: 'The Tiger of Madras',
      playerName: 'Viswanathan Anand',
      fideTitle: '15th World Champion',
      years: '1969 – Present',
      imageUrl: 'assets/player-profiles/vishwanathan-anand.webp',
      shortDescription: 'Known for lightning-fast calculating speed and intuitive sight, inspiring a grandmaster revolution in India.',
      blogSlug: 'the-tiger-of-madras-viswanathan-anand',
      category: 'World Champions',
      tags: ['Rapid Calculation', 'Speed', 'World Champion'],
      featured: false,
    },
    {
      id: 'judit-polgar',
      moniker: 'The Queen of Chess',
      playerName: 'Judit Polgár',
      fideTitle: 'Grandmaster',
      years: '1976 – Present',
      imageUrl: 'assets/player-profiles/judit-polgar.webp',
      shortDescription: 'The strongest female chess player in history, famed for her fiercely aggressive attacking style and defeat of eleven world champions.',
      blogSlug: 'the-queen-of-chess-judit-polgar',
      category: 'Tactical Masters',
      tags: ['Tactical', 'Attacking', 'Legend'],
      featured: true,
    },
    {
      id: 'hikaru-nakamura',
      moniker: 'The Speed Demon',
      playerName: 'Hikaru Nakamura',
      fideTitle: 'Grandmaster',
      years: '1987 – Present',
      imageUrl: 'assets/player-profiles/hikaru-nakamura.webp',
      shortDescription: '5-time US Champion and blitz prodigy known for unmatched speed, trickiness, and resilience under severe time pressure.',
      blogSlug: 'the-speed-demon-hikaru-nakamura',
      category: 'Modern Super GMs',
      tags: ['Blitz', 'Speed', 'Tactical'],
      featured: false,
    },
    {
      id: 'alexander-alekhine',
      moniker: 'The Stormy Petrel of Chess',
      playerName: 'Alexander Alekhine',
      fideTitle: '4th World Champion',
      years: '1892 – 1946',
      imageUrl: 'assets/player-profiles/alexander-alekhine.webp',
      shortDescription: 'Creator of complex, wild tactical combinations backed by meticulous home preparation and fierce competitive tenacity.',
      blogSlug: 'the-stormy-petrel-alexander-alekhine',
      category: 'Historical Icons',
      tags: ['Combinations', 'Complex', 'World Champion'],
      featured: false,
    },
  ]);

  readonly allMonikers = this.monikersList.asReadonly();

  getMonikers(): PlayerMoniker[] {
    return this.monikersList();
  }

  getMonikerById(id: string): PlayerMoniker | undefined {
    return this.monikersList().find((m) => m.id === id);
  }
}
